package com.wixct.pachong.web.openopen;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOPENOPEN<M extends BaseOPENOPEN<M>> extends Model<M> implements IBean {

	public M setID(Long ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public Long getID() {
		return getLong("ID");
	}

	public M setDATE(String DATE) {
		set("DATE", DATE);
		return (M)this;
	}
	
	public String getDATE() {
		return getStr("DATE");
	}

	public M setURL(String URL) {
		set("URL", URL);
		return (M)this;
	}
	
	public String getURL() {
		return getStr("URL");
	}

	public M setCOMMENT(String COMMENT) {
		set("COMMENT", COMMENT);
		return (M)this;
	}
	
	public String getCOMMENT() {
		return getStr("COMMENT");
	}

	public M setHADPARSE(Integer HADPARSE) {
		set("HADPARSE", HADPARSE);
		return (M)this;
	}
	
	public Integer getHADPARSE() {
		return getInt("HADPARSE");
	}

	public M setCOUNT(Integer COUNT) {
		set("COUNT", COUNT);
		return (M)this;
	}
	
	public Integer getCOUNT() {
		return getInt("COUNT");
	}

}
