package com.wixct.pachong.web.openopen;

import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Openopen extends BaseOPENOPEN<Openopen> {
	public static final Openopen dao = new Openopen().dao();
	/**
	 * 分页查询
	 */
	public Page<Openopen> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from OPENOPEN order by id desc");
	}
}
