package com.wixct.pachong.web.githubproject;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGITHUBPROJECT<M extends BaseGITHUBPROJECT<M>> extends Model<M> implements IBean {

	public M setID(Long ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public Long getID() {
		return getLong("ID");
	}

	public M setURL(String URL) {
		set("URL", URL);
		return (M)this;
	}
	
	public String getURL() {
		return getStr("URL");
	}

	public M setNAME(String NAME) {
		set("NAME", NAME);
		return (M)this;
	}
	
	public String getNAME() {
		return getStr("NAME");
	}

	public M setLANG(String LANG) {
		set("LANG", LANG);
		return (M)this;
	}
	
	public String getLANG() {
		return getStr("LANG");
	}

	public M setCOMMENT(String COMMENT) {
		set("COMMENT", COMMENT);
		return (M)this;
	}
	
	public String getCOMMENT() {
		return getStr("COMMENT");
	}

	public M setUPDATE(String UPDATE) {
		set("UPDATE", UPDATE);
		return (M)this;
	}
	
	public String getUPDATE() {
		return getStr("UPDATE");
	}

	public M setDESCRIPT(String DESCRIPT) {
		set("DESCRIPT", DESCRIPT);
		return (M)this;
	}
	
	public String getDESCRIPT() {
		return getStr("DESCRIPT");
	}

	public M setSTAR(Integer STAR) {
		set("STAR", STAR);
		return (M)this;
	}
	
	public Integer getSTAR() {
		return getInt("STAR");
	}

}
