package com.wixct.pachong.web.githubproject;

import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
public class Githubproject extends BaseGITHUBPROJECT<Githubproject> {
	public static final Githubproject dao = new Githubproject().dao();
	/**
	 * 分页查询
	 */
	public Page<Githubproject> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from GITHUBPROJECT order by id desc");
	}
}
